#aws_id: null
#aws_secret: null
#backup_bucket_name: ''
backup_bucket_directory: 'enjoliver'
backup_lock_key: 'backup_lock'

ignition_dict: {'kubernetes_nodes': 'kubernetes-node', 'etcd_member_kubernetes_control_plane': 'etcd-member-kubernetes-control-plane', "discovery": 'discovery'}
extra_selectors: {'os': 'installed'}

api_uri: 'http://127.0.0.1:5000'
#assets_server_uri: 'http://172.20.0.1'
#kernel: '/assets/coreos/serve/coreos_production_pxe.vmlinuz'
#initrd: '/assets/coreos/serve/coreos_production_pxe_image.cpio.gz'

matchbox_path: '/var/lib/matchbox'
matchbox_uri: 'http://127.0.0.1:8080'
matchbox_assets: '/var/lib/matchbox/assets'
matchbox_urls: ['/', '/boot.ipxe', '/boot.ipxe.0', '/assets', '/metadata']

logging_level: 'DEBUG'
matchbox_logging_level: "warning"

apply_deps_tries: 15
apply_deps_delay: 60

#matchbox_pid_file: '/opt/enjoliver/app/matchbox.pid'
#gunicorn_pid_file: '/opt/enjoliver/app/gunicorn.pid'
#plan_pid_file: '/opt/enjoliver/app/plan.pid'

gunicorn_worker_type: 'sync'
gunicorn_workers: 1
gunicorn_bind: "0.0.0.0:5000"

#db_path: '/var/lib/enjoliver/enjoliver.sqlite'

#db_uri: 'cockroachdb://root@localhost:26257'
#db_uri: 'sqlite:////var/lib/enjoliver/enjoliver.sqlite'

#ignition_journal_dir: '/var/lib/enjoliver/ignition_journal'
#werkzeug_fs_cache_dir: '/var/lib/enjoliver/werkzeug_cache'

etcd_member_kubernetes_control_plane_expected_nb: 3


fleet_etcd_data_dir: '/var/lib/etcd3/fleet'
fleet_etcd_client_port: 4001
fleet_etcd_peer_port: 7001

vault_etcd_data_dir: '/var/lib/etcd3/vault'
vault_etcd_client_port: 4002
vault_etcd_peer_port: 7002

kubernetes_etcd_data_dir: '/var/lib/etcd3/kubernetes'
kubernetes_etcd_client_port: 4003
kubernetes_etcd_peer_port: 7003

kubernetes_api_server_port: 8080

kubernetes_service_cluster_ip_range: '172.30.0.0/24'
kubernetes_apiserver_insecure_bind_address: '0.0.0.0'

skip_ips: 1
range_nb_ips: 253
sub_ips: 256

lldp_image_url: 'enjoliver.local/lldp:latest'
hyperkube_image_url: 'enjoliver.local/hyperkube:1.6.2'
rkt_image_url: 'enjoliver.local/rkt:1.25.0'
etcd_image_url: 'enjoliver.local/etcd:3.1.6'
fleet_image_url: 'enjoliver.local/fleet:1.0.0'
cni_image_url: 'enjoliver.local/cni:0.5.2'
vault_image_url: 'enjoliver.local/vault:0.7.0'

etc_hosts: ['172.20.0.1 enjoliver.local']

coreos_install_base_url: "http://enjoliver.local:5000/assets/coreos"
coreos_install_lock_seconds: 45

nameservers: ["8.8.8.8", "8.8.4.4"]
ntp: ["0.arch.pool.ntp.org", "1.arch.pool.ntp.org", "2.arch.pool.ntp.org", "3.arch.pool.ntp.org"]
fallbackntp: ["0.pool.ntp.org", "1.pool.ntp.org", "0.fr.pool.ntp.org"]

vault_polling_sec: 30